const API=window.GOLF_API_URL,$=x=>document.getElementById(x);
let courses=[];
let s={match:null,players:[],playerId:null,hole:1,course:null,scores:[]};
let deferred;
function toast(x){$('toast').textContent=x;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function page(id){['home','coursePage','matchPage'].forEach(x=>$(x).hidden=x!==id)}
function jsonp(params){return new Promise((resolve,reject)=>{const cb='ggcb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const script=document.createElement('script');let done=false;const cleanup=()=>{delete window[cb];script.remove()};const timer=setTimeout(()=>{if(done)return;done=true;cleanup();reject(new Error('API 请求超时'))},15000);window[cb]=data=>{if(done)return;done=true;clearTimeout(timer);cleanup();resolve(data)};script.onerror=()=>{if(done)return;done=true;clearTimeout(timer);cleanup();reject(new Error('NetworkError：无法连接 API'))};const q=new URLSearchParams();Object.entries(params||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null)q.set(k,typeof v==='object'?JSON.stringify(v):String(v))});q.set('callback',cb);script.src=API+'?'+q.toString();document.head.appendChild(script)})}
async function get(p){return jsonp(p)}
async function post(x){return jsonp(x)}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function normalizeCourse(c){return {course_id:c.course_id||c.id,course_name:c.course_name||c.name,holes:(c.holes||[]).map((h,i)=>({hole:+(h.hole||i+1),par:+h.par,si:+h.si}))}}
async function loadCourses(){try{const r=await get({action:'getCourses'});if(!r.success)throw Error(r.error||'读取球场失败');courses=(r.courses||[]).map(normalizeCourse);renderCourseSelect();renderSaved()}catch(e){toast('读取球场失败：'+e.message)}}
function renderCourseSelect(){$('course').innerHTML='<option value="">请选择球场</option>'+courses.map(c=>`<option value="${esc(c.course_id)}">${esc(c.course_name)}</option>`).join('')}
function renderSaved(){$('saved').innerHTML=courses.length?courses.map(c=>`<div class="courseitem"><b>${esc(c.course_name)}</b><br><small>${esc(c.course_id)} · 18洞 Par / SI</small></div>`).join(''):'暂无球场，请新增。'}
function holeEditor(){$('holes').innerHTML=Array.from({length:18},(_,i)=>`<div class="hr"><b>Hole ${i+1}</b><input class="par" value="4" type="number" min="3" max="6"><input class="si" value="${i+1}" type="number" min="1" max="18"></div>`).join('')}
$('courses').onclick=()=>{page('coursePage');$('cname').value='';holeEditor();renderSaved()}
$('saveCourse').onclick=async()=>{const name=$('cname').value.trim();if(!name)return toast('请输入球场名称');const holes=[...document.querySelectorAll('.hr')].map((r,i)=>({hole:i+1,par:+r.querySelector('.par').value,si:+r.querySelector('.si').value}));if(holes.some(h=>!Number.isInteger(h.par)||h.par<3||h.par>6||!Number.isInteger(h.si)||h.si<1||h.si>18)||new Set(holes.map(h=>h.si)).size!==18)return toast('Par 必须 3–6，SI 必须 1–18 且各一次');const dup=courses.some(c=>c.course_name.trim().toLowerCase()===name.toLowerCase());if(dup)return toast('这个球场已经存在');$('saveCourse').disabled=true;try{const r=await post({action:'createCourse',course_name:name,holes});if(!r.success)return toast(r.error||'保存失败');toast('球场已永久保存');await loadCourses();$('cname').value='';holeEditor()}catch(e){toast('保存失败：'+e.message)}finally{$('saveCourse').disabled=false}}
$('create').onclick=async()=>{const admin=$('admin').value.trim(),course_id=$('course').value;if(!admin)return toast('请输入管理员姓名');if(!course_id)return toast('请选择球场');$('create').disabled=true;try{const r=await post({action:'createMatch',admin,player_count:+$('count').value,course_id});if(!r.success)return toast(r.error||'创建失败');s={match:null,players:[],playerId:null,hole:1,course:null,scores:[]};await enter(r.match_id);toast('比赛编号：'+r.match_id)}catch(e){toast('创建失败：'+e.message)}finally{$('create').disabled=false}}
$('join').onclick=async()=>{const match_id=$('mid').value.trim().toUpperCase(),name=$('name').value.trim();if(!match_id||!name)return toast('请输入比赛编号和姓名');$('join').disabled=true;try{const r=await post({action:'joinMatch',match_id,name});if(!r.success)return toast(r.error||'加入失败');s.playerId=r.player_id;alert('你的加入码：'+r.join_code);await enter(r.match_id)}catch(e){toast('加入失败：'+e.message)}finally{$('join').disabled=false}}
async function enter(id){const r=await get({action:'getMatch',match_id:id});if(!r.success)return toast(r.error||'读取比赛失败');s.match=r.match;s.players=r.players||[];const cid=r.match.course_id||r.course_id;if(cid){s.course=courses.find(c=>c.course_id===cid)||null;if(!s.course){try{const cr=await get({action:'getCourse',course_id:cid});if(cr.success)s.course=normalizeCourse(cr.course)}catch(_){}}}$('matchId').textContent=id;$('courseName').textContent=s.course?.course_name||'球场资料未找到';page('matchPage');renderMatch();await refresh()}
function renderMatch(){const h=s.course?.holes?.find(x=>x.hole===s.hole);$('hole').textContent=s.hole;$('parsi').textContent=h?`PAR ${h.par} · SI ${h.si}`:'PAR — · SI —';$('players').innerHTML=s.players.map(p=>`<div class="row"><span>${esc(p.name)}</span><small>${esc(p.player_id)}</small></div>`).join('');const m=s.scores.find(x=>x.player_id===s.playerId);$('mine').innerHTML=s.playerId?`<label>杆数<input id="sc" type="number" min="1" max="20" value="${m?.score??''}"></label><label><input id="up" type="checkbox" style="display:inline;width:auto" ${m?.up?'checked':''}> UP</label><button onclick="submitScore()">提交</button>`:'请先加入比赛'}
window.submitScore=async()=>{const score=+$('sc').value;if(!score)return toast('请输入杆数');try{const r=await post({action:'submitScore',match_id:s.match.match_id,player_id:s.playerId,hole:s.hole,score,up:$('up').checked,submitted_by:s.playerId});toast(r.success?'已提交':r.error||'提交失败');if(r.success)refresh()}catch(e){toast('提交失败：'+e.message)}}
async function refresh(){if(!s.match)return;try{const r=await get({action:'getScores',match_id:s.match.match_id,hole:s.hole});if(r.success){s.scores=r.scores||[];$('scores').innerHTML=s.scores.length?s.scores.map(x=>`<div class="row"><span>${esc((s.players.find(p=>p.player_id===x.player_id)||{}).name||x.player_id)}</span><b>${x.score}</b>${x.up?'<span class="up">UP</span>':''}</div>`).join(''):'暂无成绩';renderMatch()}}catch(e){}}
$('prev').onclick=()=>{if(s.hole>1){s.hole--;renderMatch();refresh()}};$('next').onclick=()=>{if(s.hole<18){s.hole++;renderMatch();refresh()}};document.querySelectorAll('.back').forEach(b=>b.onclick=()=>page('home'));setInterval(()=>{if(!$('matchPage').hidden)refresh()},8000);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('install').hidden=false});$('install').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js');
holeEditor();loadCourses();
