const API='https://script.google.com/macros/s/AKfycbzIr3lOr5a8IaA51ixM8xta_RgOjLooxmlk2mRosDti5jJIMTKEVUR2qeSPckzhQo1T/exec';
const state={view:'home',courses:[],match:null,course:null,players:[],scores:[],handicaps:{},selectedPlayers:4,currentMode:'F9',currentHole:1,currentPlayer:null,isAdmin:false,adminName:'',editingScore:null,editingScores:null,editingHole:null,scoreMap:{},courseMap:{},qr:false,error:''};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function post(data){return fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)}).then(r=>r.json())}
function get(action,params={}){const q=new URLSearchParams({action,...params});return fetch(API+'?'+q.toString()).then(r=>r.json())}
function localName(gameId){return localStorage.getItem('golf-name-'+gameId)||''} function saveLocalName(gameId,name){localStorage.setItem('golf-name-'+gameId,name)}
function render(){document.getElementById('app').innerHTML=state.view==='home'?homeView():state.view==='new'?newGameView():state.view==='join'?joinView():state.view==='courses'?coursesView():scoreView();}
function shell(content,opts={}){return `<div class="app-shell"><header class="header"><div>${opts.back?`<button class="back" onclick="goHome()">‹ Home</button>`:`<div class="brand">Golf Game${state.match?` <small>${esc(state.match.match_id)}</small>`:''}</div>`}</div>${opts.qr?`<button class="qr-btn" onclick="openQR()" aria-label="QR">⌁</button>`:''}</header>${content}</div>`}
function homeView(){return shell(`<main class="container home"><div class="home-title">Golf Game</div><div class="sub">Simple mobile scoring for your game.</div><div class="home-buttons"><button class="big-btn primary" onclick="show('join')"><span>Join Game</span><span class="arrow">›</span></button><button class="big-btn secondary" onclick="show('new')"><span>＋ New Game</span><span class="arrow">›</span></button><button class="big-btn tertiary" onclick="show('courses')"><span>⚑ Course</span><span class="arrow">›</span></button></div></main>`)}
function newGameView(){return shell(`<main class="container"><div class="card"><div class="section-head"><div class="section-title">New Game</div></div><div id="new-error"></div><div class="form-row"><div class="label">Game ID</div><input id="gameId" class="field" placeholder="Enter Game ID"></div><div class="form-row"><div class="label">Course</div><select id="courseId" class="field"><option value="">Select Course</option>${state.courses.map(c=>`<option value="${esc(c.course_id)}">${esc(c.course_name)}</option>`).join('')}</select></div><div class="form-row"><div class="label">Players</div><div class="num-row">${[2,3,4,5,6].map(n=>`<button class="num-btn ${state.selectedPlayers===n?'active':''}" onclick="selectPlayers(${n})">${n}</button>`).join('')}</div></div><div class="form-row"><div class="label">Player Names</div><div class="player-grid">${Array.from({length:state.selectedPlayers},(_,i)=>`<input class="field pname" data-i="${i}" placeholder="Player ${i+1}">`).join('')}</div></div><div class="card" style="margin:16px 0 0;padding:14px;background:#f5faf8;border-color:#d8ebe5"><div class="section-head"><div><div class="section-title" style="font-size:16px">Handicap</div><div style="font-size:12px;color:#667872">Set pair handicaps before Start.</div></div><button class="link-btn" onclick="openHandicap()">Edit ›</button></div></div><button class="start primary" onclick="startGame()">Start</button></div></main>`);loadCoursesIfNeeded()}
function joinView(){return shell(`<main class="container"><div class="card"><div class="section-title" style="margin-bottom:18px">Join Game</div><div id="join-error"></div><div class="form-row"><div class="label">Game ID</div><input id="joinGameId" class="field" placeholder="Enter Game ID"></div><div class="form-row"><div class="label">Your Name</div><input id="joinName" class="field" placeholder="Enter your name"></div><button class="start primary" onclick="joinGame()">Join</button><div style="margin-top:12px;color:#697972;font-size:12px">Your name is saved on this device for next time.</div></div></main>`)}
function coursesView(){return shell(`<main class="container"><div class="card"><div class="section-head"><div class="section-title">Course</div><button class="link-btn" onclick="newCoursePrompt()">＋ Add</button></div><div class="course-list">${state.courses.map(c=>`<button class="course-item" onclick="courseDetail('${esc(c.course_id)}')"><span><strong>${esc(c.course_name)}</strong><small>18 holes</small></span><span>›</span></button>`).join('')}</div></div></main>`)}
function courseDetail(id){const c=state.courses.find(x=>x.course_id===id);if(!c)return;document.getElementById('app').innerHTML=shell(`<main class="container"><div class="card course-detail"><div class="section-title" style="margin-bottom:12px">${esc(c.course_name)}</div><table><thead><tr><th>Hole</th><th>PAR</th><th>Index</th></tr></thead><tbody>${c.holes.map(h=>`<tr><td>${h.hole}</td><td>${h.par}</td><td>${h.si}</td></tr>`).join('')}</tbody></table></div></main>`,{back:true})}
function selectPlayers(n){state.selectedPlayers=n;render()}
async function loadCoursesIfNeeded(){if(state.courses.length)return;try{const r=await get('getCourses');if(r.success){state.courses=r.courses;updateCourseSelect()}}catch(e){console.warn('getCourses failed',e)}}
function updateCourseSelect(){const el=$('courseId');if(!el)return;const current=el.value;el.innerHTML='<option value="">Select Course</option>'+state.courses.map(c=>`<option value="${esc(c.course_id)}">${esc(c.course_name)}</option>`).join('');if(current)el.value=current}
async function show(v){state.view=v;state.error='';render();if(v==='new'||v==='courses')await loadCoursesIfNeeded()}
function goHome(){state.view='home';render()}
async function startGame(){const err=$('new-error');err.innerHTML='';const gameId=$('gameId').value.trim(),courseId=$('courseId').value, names=[...document.querySelectorAll('.pname')].map(x=>x.value.trim());if(!gameId||!courseId||names.some(n=>!n)||new Set(names.map(n=>n.toLowerCase())).size!==names.length){err.innerHTML='<div class="error">Enter Game ID, Course and unique player names.</div>';return}const r=await post({action:'createMatch',match_id:gameId,admin:names[0],course_id:courseId,players:names,handicaps:state.handicaps});if(!r.success){err.innerHTML=`<div class="error">${esc(r.error)}</div>`;return}if(Number(r.handicap_rows||0)!==names.length*(names.length-1)){err.innerHTML='<div class="error">Handicap was not saved. Please run setupDatabase() and redeploy the Apps Script.</div>';return}state.adminName=names[0];state.isAdmin=true;saveLocalName(gameId,names[0]);await openMatch(gameId,names[0],true)}
async function joinGame(){const err=$('join-error');err.innerHTML='';const id=$('joinGameId').value.trim(),name=$('joinName').value.trim();if(!id||!name){err.innerHTML='<div class="error">Enter Game ID and your name.</div>';return}const r=await post({action:'joinMatch',match_id:id,name});if(!r.success){err.innerHTML=`<div class="error">${esc(r.error)}</div>`;return}saveLocalName(id,name);state.adminName='';state.isAdmin=false;await openMatch(id,name,false)}
async function openMatch(id,name,isAdmin){const [r,s]=await Promise.all([get('getMatch',{match_id:id}),get('getScores',{match_id:id})]);if(!r.success){alert(r.error);return}state.match=r.match;state.players=r.players;state.course=r.course;state.courseMap={};(state.course.holes||[]).forEach(h=>state.courseMap[Number(h.hole)]=h);state.handicaps=r.handicaps||{};state.scores=s.success?s.scores:[];state.scoreMap={};state.scores.forEach(x=>state.scoreMap[`${x.player_id}|${Number(x.hole)}`]=x);state.currentPlayer=state.players.find(p=>p.name.toLowerCase()===name.toLowerCase())||state.players[0];state.isAdmin=isAdmin||name.toLowerCase()===String(state.match.admin||'').toLowerCase();state.view='score';render()}
function openHandicap(){const names=[...document.querySelectorAll('.pname')].map(x=>x.value.trim());if(names.length<2||names.some(n=>!n)){alert('Enter all player names first.');return}state.handicapNames=names;state.handicapDraft={...state.handicaps};const div=document.createElement('div');div.className='handicap-modal';div.id='handicapModal';div.innerHTML=handicapHTML(names);document.body.appendChild(div);bindHandicap()} 
function handicapHTML(names){let h='<div class="handicap-panel"><div class="modal-top"><div class="section-title">Handicap Matrix</div><button class="close" onclick="closeHandicap()">×</button></div><div class="help">Select the handicap. <b>Negative = give strokes</b>, <b>0 = square</b>, <b>Positive = receive strokes</b>. The reverse side is automatic.</div><div class="matrix-wrap"><table class="matrix"><thead><tr><th>GIVE</th>'+names.map(n=>`<th>${esc(n)}</th>`).join('')+'</tr></thead><tbody>';names.forEach((row,i)=>{h+=`<tr><td>${esc(row)}</td>`;names.forEach((col,j)=>{if(i===j)h+='<td class="diag">—</td>';else if(j<i){const v=-(Number(state.handicapDraft[`${i}-${j}`]??0));h+=`<td class="auto-value ${v<0?'neg':v>0?'pos':'zero'}">${v>0?'+':''}${v}</td>`}else{const key=`${i}-${j}`,v=Number(state.handicapDraft[key]??0);h+=`<td><select class="handicap-select ${v<0?'neg':v>0?'pos':'zero'}" data-key="${key}">${Array.from({length:29},(_,k)=>k-14).map(n=>`<option value="${n}" ${n===v?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></td>`}});h+='</tr>'});h+='</tbody></table></div><div class="legend"><span class="neg">● -14 to -1 Give</span><span class="zero">● 0 Square</span><span class="pos">● +1 to +14 Receive</span></div><div class="modal-actions"><button class="cancel" onclick="closeHandicap()">Cancel</button><button class="save" onclick="saveHandicap()">Save</button></div></div>';return h}
function bindHandicap(){document.querySelectorAll('.handicap-select').forEach(s=>s.addEventListener('change',()=>{const v=Number(s.value);state.handicapDraft[s.dataset.key]=v;s.className='handicap-select '+(v<0?'neg':v>0?'pos':'zero');document.getElementById('handicapModal').innerHTML=handicapHTML(state.handicapNames);bindHandicap()}))}
function saveHandicap(){state.handicaps={...state.handicapDraft};closeHandicap()}
function closeHandicap(){document.getElementById('handicapModal')?.remove()}
function scoreFor(pid,hole){return state.scoreMap[`${pid}|${Number(hole)}`]||{score:'',up:false}}
function courseHole(hole){return state.courseMap[Number(hole)]||null}
function getPairHandicap(a,b){const ia=state.players.findIndex(p=>p.player_id===a),ib=state.players.findIndex(p=>p.player_id===b);if(ia<0||ib<0)return 0;const key=ia<ib?`${ia}-${ib}`:`${ib}-${ia}`;const base=Number(state.handicaps[key]||0);return ia<ib?base:-base}
function segmentStrokeCount(total,mode){const n=Math.abs(Number(total)||0);if(mode==='F9'||mode==='B9')return n/2;return n}
function strokeValueForHole(a,b,hole){const hc=getPairHandicap(a,b);if(hc===0)return 0;const mode=hole<=9?'F9':'B9';const count=segmentStrokeCount(hc,mode);if(!count)return 0;const start=hole<=9?1:10;const end=hole<=9?9:18;const candidates=(state.course?.holes||[]).filter(x=>Number(x.hole)>=start&&Number(x.hole)<=end).sort((x,y)=>Number(x.si)-Number(y.si));const absCount=Math.abs(count);const full=Math.floor(absCount);const half=absCount-full;const idx=candidates.findIndex(x=>Number(x.hole)===Number(hole));if(idx<0||idx>=full+(half?1:0))return 0;const amount=idx<full?1:0.5;return hc<0?-amount:amount}
function strokesFor(a,b,hole){return strokeValueForHole(a,b,hole)}
function fmtStroke(n){if(!n)return '0';return `${n>0?'+':''}${Number.isInteger(n)?n:n.toFixed(1)}`}
function segmentHandicap(a,b,mode){const hc=getPairHandicap(a,b);const n=segmentStrokeCount(hc,mode);return hc<0?-n:n}
function relative(a,b,hole){const sa=Number(scoreFor(a,hole).score),sb=Number(scoreFor(b,hole).score);if(!sa||!sb)return 'S';const stroke=strokesFor(a,b,hole);const adjA=sa-stroke;return adjA<sb?'W':adjA>sb?'L':'S'}
function cellClass(viewer,pid,hole){if(pid===viewer)return '';const st=strokesFor(viewer,pid,hole);if(st>0)return 'benefit';if(st<0)return 'disadvantage';return ''}
function isBirdie(score,par){return score&&score<=par-1}
function scoreMarkup(pid,hole){const s=scoreFor(pid,hole);if(s.score==='')return '<span style="color:#a1aaa6">–</span>';const par=Number(courseHole(hole)?.par||4);const score=Number(s.score);if(score<par)return `<span class="double-circle">${s.score}</span>`;if(score===par)return `<span class="circle">${s.score}</span>`;return `<span>${s.score}</span>`}
function pairOutcomes(viewer,opp,mode){const holes=mode==='F9'?Array.from({length:9},(_,i)=>i+1):Array.from({length:9},(_,i)=>i+10);let margin=0;let decisionAt=null;const rows=[];for(const h of holes){const a=Number(scoreFor(viewer,h).score),b=Number(scoreFor(opp,h).score);let r='S';if(a&&b){r=relative(viewer,opp,h);if(r==='W')margin++;else if(r==='L')margin--}const remainingAfter=holes[holes.length-1]-h;if(decisionAt===null&&a&&b&&Math.abs(margin)>remainingAfter)decisionAt=h;rows.push({h,r,margin,decisionAt})}return {holes,rows,decisionAt,finalMargin:margin}}
function fmtState(n,wordUp='UP',wordDown='DW'){if(n>0)return `${n}${wordUp}`;if(n<0)return `${Math.abs(n)}${wordDown}`;return 'SQUARE'}
function matchStatus(viewer,opp,hole){const mode=state.currentMode==='B9'?'B9':'F9';const {holes,rows,decisionAt}=pairOutcomes(viewer,opp,mode);const idx=rows.findIndex(x=>x.h===hole);if(idx<0)return '–';const row=rows[idx];if(decisionAt===null||hole<decisionAt)return fmtState(row.margin);const dIdx=rows.findIndex(x=>x.h===decisionAt);if(dIdx<0)return fmtState(row.margin);if(idx===dIdx){const t=row.r==='W'?1:row.r==='L'?-1:0;return t?`G/T${t>0?'+':''}${t}`:'G'}let t=0,b=0;for(let i=dIdx;i<=idx;i++){const r=rows[i].r;if(r==='W')t++;else if(r==='L')t--;if(i>dIdx){if(r==='W')b++;else if(r==='L')b--}}return `T${t>0?'+':''}${t}/B${b>0?'+':''}${b}`}
function matchStatusClass(text){if(text==='G'||text.startsWith('G/'))return 'status-game';if(/UP/.test(text)||/T\+|B\+/.test(text))return 'status-up';if(/DW/.test(text)||/T-|B-/.test(text))return 'status-down';return 'status-square'}
function matchHandicapLabel(viewer,opp){const mode=state.currentMode==='B9'?'B9':'F9';const n=segmentHandicap(viewer,opp,mode);return `Match ${fmtStroke(n)}`}
function scoreView(){return shell(`<main class="score-page"><div class="mode-tabs">${['F9','B9','Baccarat'].map(m=>`<button class="mode-tab ${state.currentMode===m?'active':''}" onclick="setMode('${m}')">${m}</button>`).join('')}</div>${state.currentMode==='Baccarat'?baccaratTable():matchTable()}${state.editingScores?bulkScoreEditor():state.editingScore?scoreEditor():''}${state.qr?qrModal():''}</main>`,{qr:true})}
function holesForMode(){return state.currentMode==='F9'?Array.from({length:9},(_,i)=>i+1):state.currentMode==='B9'?Array.from({length:9},(_,i)=>i+10):Array.from({length:18},(_,i)=>i+1)}
function matchTable(){const holes=holesForMode();return `<div class="score-scroll"><table class="score-table"><thead><tr><th>Holes</th>${holes.map(h=>`<th>${h}</th>`).join('')}</tr><tr><th>Index</th>${holes.map(h=>`<th>${courseHole(h)?.si||''}</th>`).join('')}</tr><tr><th>PAR</th>${holes.map(h=>`<th>${courseHole(h)?.par||''}</th>`).join('')}</tr></thead><tbody>${state.players.map((p,pi)=>`<tr class="player-row ${pi%2?'alt':''}"><td class="player-name">${esc(p.name)}${p.player_id===state.currentPlayer.player_id?'<div class="you">YOU</div>':`<div class="match-hcp">${matchHandicapLabel(state.currentPlayer.player_id,p.player_id)}</div>`}</td>${holes.map(h=>`<td class="score-cell ${cellClass(state.currentPlayer.player_id,p.player_id,h)} ${((p.player_id===state.currentPlayer.player_id)||state.isAdmin)?'editable':''}" onclick="editScore('${p.player_id}',${h})">${scoreMarkup(p.player_id,h)}</td>`).join('')}</tr>${p.player_id!==state.currentPlayer.player_id?`<tr class="stroke-row ${pi%2?'alt':''}"><td><span class="match-status-label">MATCH</span></td>${holes.map(h=>{const ms=matchStatus(state.currentPlayer.player_id,p.player_id,h);return `<td class="match-status-cell ${matchStatusClass(ms)}">${ms}</td>`}).join('')}</tr>`:''}`).join('')}</tbody></table></div><div class="score-tools"><button class="nav-btn" onclick="prevHole()">‹ Prev</button><span class="hole-count">Hole ${state.currentHole} / ${state.currentMode==='F9'?9:state.currentMode==='B9'?18:18}</span><button class="nav-btn" onclick="nextHole()">Next ›</button></div>${resultPanel()}`}
function resultForOpponent(pid,mode){const me=state.currentPlayer.player_id;const holes=mode==='F9'?Array.from({length:9},(_,i)=>i+1):Array.from({length:9},(_,i)=>i+10);const {decisionAt,finalMargin}=pairOutcomes(me,pid,mode);let game=0,tommy=0,buy=0;if(finalMargin>0)game=3;else if(finalMargin<0)game=-3;else game=-1;if(finalMargin!==0&&decisionAt!==null&&decisionAt<holes[holes.length-1]){tommy=finalMargin>0?1:-1;buy=finalMargin>0?1:-1}const myBonus=bonusBreakdown(me,mode).bonus;const oppBonus=bonusBreakdown(pid,mode).bonus;const bonus=myBonus-oppBonus;return {game,tommy,buy,bonus,total:game+tommy+buy+bonus}}
function resultPanel(){const mode=state.currentMode==='B9'?'B9':'F9';const pairs=[];for(let i=0;i<state.players.length;i++){for(let j=i+1;j<state.players.length;j++){const a=state.players[i],b=state.players[j];const r=resultForOpponent(a.player_id,b.player_id,mode);pairs.push({label:`${a.name} v ${b.name}`,r})}}return `<div class="result-card"><div class="result-title">${mode==='F9'?'Front 9 Result':'Back 9 Result'}</div><div class="result-scroll"><table class="result-table"><thead><tr><th>Opponent</th><th>Game</th><th>Tommy</th><th>Buy</th><th>Bonus</th><th>Total</th></tr></thead><tbody>${pairs.map(x=>{const r=x.r;return `<tr><td>${esc(x.label)}</td><td>${fmtSigned(r.game)}</td><td>${fmtSigned(r.tommy)}</td><td>${fmtSigned(r.buy)}</td><td>${fmtSigned(r.bonus)}</td><td><b>${fmtSigned(r.total)}</b></td></tr>`}).join('')}</tbody></table></div></div>`}
function bonusBreakdown(pid,mode){const holes=mode==='F9'?Array.from({length:9},(_,i)=>i+1):Array.from({length:9},(_,i)=>i+10);const data={double3:0,double5:0,birdie:0,eagle:0,hio:0,bonus:0};const rows=holes.map(h=>{const score=Number(scoreFor(pid,h).score);const par=Number(courseHole(h)?.par||0);return {score,par}});const par3=rows.filter(x=>x.par===3);const par5=rows.filter(x=>x.par===5);if(par3.length===2&&par3.every(x=>x.score>0&&x.score<=x.par))data.double3=1;if(par5.length===2&&par5.every(x=>x.score>0&&x.score<=x.par))data.double5=1;rows.forEach(x=>{if(!x.score||!x.par)return;if(x.par===3&&x.score===1){data.hio+=12;return}if(x.score<=x.par-2){data.eagle+=6;return}if(x.score===x.par-1)data.birdie+=1});data.bonus=data.double3+data.double5+data.birdie+data.eagle+data.hio;return data}
function fmtSigned(n){return n>0?`+${n}`:String(n)}
function baccaratTable(){const holes=Array.from({length:18},(_,i)=>i+1);return `<div class="score-scroll"><table class="score-table"><thead><tr><th>Holes</th>${holes.map(h=>`<th>${h}</th>`).join('')}<th>Total</th></tr><tr><th>Index</th>${holes.map(h=>`<th>${courseHole(h)?.si||''}</th>`).join('')}<th>—</th></tr><tr><th>PAR</th>${holes.map(h=>`<th>${courseHole(h)?.par||''}</th>`).join('')}<th>—</th></tr></thead><tbody>${state.players.map((p,pi)=>`<tr class="player-row ${pi%2?'alt':''}"><td class="player-name">${esc(p.name)}${p.player_id===state.currentPlayer.player_id?'<div class="you">YOU</div>':''}</td>${holes.map(h=>`<td>${baccaratPoints(p.player_id,h)}</td>`).join('')}<td><b>${holes.reduce((a,h)=>a+baccaratPoints(p.player_id,h),0)}</b></td></tr>`).join('')}</tbody></table></div><div class="score-tools"><button class="nav-btn" onclick="prevHole()">‹ Prev</button><span class="hole-count">Hole ${state.currentHole} / 18</span><button class="nav-btn" onclick="nextHole()">Next ›</button></div>`}
function baccaratPoints(pid,hole){const s=Number(scoreFor(pid,hole).score);if(!s)return 0;const par=courseHole(hole)?.par||4;if(par===3&&s===1)return 32;let pts=1;if(s<=par-2)pts=4;else if(s===par-1)pts=2;const up=scoreFor(pid,hole).up;return up?pts*2:pts}
function setMode(m){state.currentMode=m;state.currentHole=m==='B9'?10:1;render()}function prevHole(){state.currentHole=Math.max(state.currentMode==='B9'?10:1,state.currentHole-1);render()}function nextHole(){const max=state.currentMode==='F9'?9:18;state.currentHole=Math.min(max,state.currentHole+1);render()}
function editScore(pid,hole){if(pid!==state.currentPlayer.player_id&&!state.isAdmin)return;if(state.isAdmin){state.editingHole=hole;state.editingScores=state.players.map(p=>({pid:p.player_id,name:p.name,...scoreFor(p.player_id,hole)}));state.editingScore=null;render()}else{state.editingScore={pid,hole,...scoreFor(pid,hole)};render()}}
function scoreEditor(){const e=state.editingScore;return `<div class="score-editor"><div class="editor-panel"><div class="editor-title">Edit Score</div><div class="editor-sub">${esc(state.players.find(p=>p.player_id===e.pid)?.name||'')} · Hole ${e.hole}</div><div class="score-picker">${Array.from({length:12},(_,i)=>i+1).map(n=>`<button class="score-option ${Number(e.score)===n?'active':''}" onclick="pickScore(${n})">${n}</button>`).join('')}</div><label class="up-row"><input id="editUp" type="checkbox" ${e.up?'checked':''}> UP</label><div class="editor-actions"><button class="cancel-score" onclick="cancelEdit()">Cancel</button><button class="save-score" onclick="saveEditedScore()">Save</button></div></div></div>`}
function bulkScoreEditor(){const hole=state.editingHole;const rows=state.editingScores||[];return `<div class="score-editor"><div class="editor-panel bulk-editor"><div class="editor-title">Admin · Hole ${hole}</div><div class="editor-sub">Enter all players' score and UP at once.</div><div class="bulk-list">${rows.map((r,i)=>`<div class="bulk-row"><div class="bulk-name">${esc(r.name)}</div><div class="bulk-score">${Array.from({length:12},(_,n)=>n+1).map(n=>`<button class="bulk-score-btn ${Number(r.score)===n?'active':''}" onclick="pickBulkScore(${i},${n})">${n}</button>`).join('')}</div><label class="bulk-up"><input type="checkbox" ${r.up?'checked':''} onchange="pickBulkUp(${i},this.checked)"> UP</label></div>`).join('')}</div><div class="editor-actions"><button class="cancel-score" onclick="cancelBulkEdit()">Cancel</button><button class="save-score" onclick="saveBulkScores()">Save All</button></div></div></div>`}
function pickScore(n){state.editingScore.score=n;render()}function cancelEdit(){state.editingScore=null;render()}
function pickBulkScore(i,n){state.editingScores[i].score=n;render()}function pickBulkUp(i,v){state.editingScores[i].up=v}
async function saveEditedScore(){const e=state.editingScore;const up=document.getElementById('editUp').checked;const r=await post({action:'saveScore',match_id:state.match.match_id,hole:e.hole,player_id:e.pid,score:e.score,up,submitted_by:state.currentPlayer.player_id});if(!r.success){alert(r.error);return}const old=state.scores.find(s=>s.player_id===e.pid&&Number(s.hole)===e.hole);if(old){old.score=e.score;old.up=up}else {const added={player_id:e.pid,hole:e.hole,score:e.score,up};state.scores.push(added)}state.scoreMap[`${e.pid}|${e.hole}`]=state.scores.find(x=>x.player_id===e.pid&&Number(x.hole)===Number(e.hole));state.editingScore=null;render()}
async function saveBulkScores(){const rows=state.editingScores||[];if(rows.some(r=>!r.score)){alert('Enter a score for every player.');return}const payload=rows.map(x=>({player_id:x.pid,score:Number(x.score),up:!!x.up}));let r=await post({action:'saveScoresBatch',match_id:state.match.match_id,hole:state.editingHole,scores:payload,submitted_by:state.currentPlayer.player_id});if(!r.success&&String(r.error||'').includes('Unknown action: saveScoresBatch')){const results=await Promise.all(payload.map(x=>post({action:'saveScore',match_id:state.match.match_id,hole:state.editingHole,player_id:x.player_id,score:x.score,up:x.up,submitted_by:state.currentPlayer.player_id})));const bad=results.find(x=>!x.success);if(bad)r=bad;else r={success:true}}if(!r.success){alert(r.error||'Save failed');return}rows.forEach(x=>{const old=state.scores.find(s=>s.player_id===x.pid&&Number(s.hole)===state.editingHole);if(old){old.score=Number(x.score);old.up=!!x.up}else {const added={player_id:x.pid,hole:state.editingHole,score:Number(x.score),up:!!x.up};state.scores.push(added)}state.scoreMap[`${x.pid}|${state.editingHole}`]=state.scores.find(s=>s.player_id===x.pid&&Number(s.hole)===Number(state.editingHole))});state.editingScores=null;state.editingHole=null;render()}
function cancelBulkEdit(){state.editingScores=null;state.editingHole=null;render()}
function qrModal(){return `<div class="handicap-modal" onclick="if(event.target===this)state.qr=false,render()"><div class="handicap-panel" style="text-align:center"><div class="modal-top"><div class="section-title">Join Game</div><button class="close" onclick="state.qr=false;render()">×</button></div><div style="width:220px;height:220px;margin:20px auto;background:repeating-linear-gradient(45deg,#111 0 4px,#fff 4px 8px);border:14px solid #fff;box-shadow:0 0 0 1px #ddd"></div><div style="font-size:24px;font-weight:900">${esc(state.match.match_id)}</div><div class="help">Scan this QR code to join the game</div><div class="notice">Players ${state.players.length} · Joined ${state.players.length} / ${state.match.player_count}</div></div></div>`}
function openQR(){state.qr=true;render()}
function newCoursePrompt(){alert('Use your existing Course editor to add or edit courses. Course data remains permanent.')} 
loadCoursesIfNeeded();render();
